apiVersion: rafter.kyma-project.io/v1beta1
kind: ClusterAssetGroup
metadata:
  labels:
    rafter.kyma-project.io/view-context: docs-ui
    rafter.kyma-project.io/group-name: components
    rafter.kyma-project.io/order: "15"
  name: rafter
spec:
  displayName: "Rafter"
  description: "Overall documentation for Rafter"
  sources:
    - type: markdown
      name: docs
      mode: package
      url: https://github.com/{{ .Values.global.kymaOrgName }}/kyma/archive/{{ .Values.global.docs.clusterAssetGroupsVersion }}.zip
      filter: /docs/rafter/
    - type: openapi
      name: rafter-upload-service-openapi
      mode: single
      url: https://raw.githubusercontent.com/{{ .Values.global.kymaOrgName }}/kyma/{{ .Values.global.docs.clusterAssetGroupsVersion }}/docs/rafter/assets/rafter-upload-service-openapi.yaml
    - type: openapi
      name: rafter-front-matter-service-openapi
      mode: single
      url: https://raw.githubusercontent.com/{{ .Values.global.kymaOrgName }}/kyma/{{ .Values.global.docs.clusterAssetGroupsVersion }}/docs/rafter/assets/rafter-front-matter-service-openapi.yaml
    - type: openapi
      name: rafter-asyncapi-service-openapi
      mode: single
      url: https://raw.githubusercontent.com/{{ .Values.global.kymaOrgName }}/kyma/{{ .Values.global.docs.clusterAssetGroupsVersion }}/docs/rafter/assets/rafter-asyncapi-service-openapi.yaml
    - type: openapi
      name: example-openapi-service
      mode: single
      url: https://raw.githubusercontent.com/{{ .Values.global.kymaOrgName }}/kyma/{{ .Values.global.docs.clusterAssetGroupsVersion }}/docs/rafter/assets/example-openapi-service.yaml