required = [
  "github.com/golang/lint/golint",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/asyncapi/parser"
  branch = "master"
[[constraint]]
  name = "github.com/vrischmann/envconfig"
  version = "1.2.0"
