required = [
  "github.com/golang/lint/golint",
  "golang.org/x/tools/cmd/goimports",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/asyncapi/parser"
  branch = "master"

[[constraint]]
  name = "github.com/asyncapi/converter-go"
  source = "github.com/m00g3n/converter-go"
  branch = "imports"

[[constraint]]
  name = "github.com/vrischmann/envconfig"
  version = "1.2.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.5.0"
