// Code generated by mockery v1.0.0
package automock

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// HttpEndpoint is an autogenerated mock type for the HttpEndpoint type
type HttpEndpoint struct {
	mock.Mock
}

// Handle provides a mock function with given fields: writer, request
func (_m *HttpEndpoint) Handle(writer http.ResponseWriter, request *http.Request) {
	_m.Called(writer, request)
}

// Name provides a mock function with given fields:
func (_m *HttpEndpoint) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
