// Code generated by mockery v1.0.0
package automock

import context "context"
import mock "github.com/stretchr/testify/mock"
import service "github.com/kyma-project/kyma/components/cms-services/pkg/runtime/service"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Register provides a mock function with given fields: endpoint
func (_m *Service) Register(endpoint service.HttpEndpoint) {
	_m.Called(endpoint)
}

// Start provides a mock function with given fields: ctx
func (_m *Service) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
