// Code generated by mockery v1.0.0
package automock

import context "context"

import io "io"
import mock "github.com/stretchr/testify/mock"

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: ctx, contentType, reader, metadata
func (_m *Validator) Validate(ctx context.Context, contentType string, reader io.Reader, metadata string) error {
	ret := _m.Called(ctx, contentType, reader, metadata)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, string) error); ok {
		r0 = rf(ctx, contentType, reader, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
